/** Shared constants for dashboard and worker. */

export const BOT_STATUSES = ['stopped', 'starting', 'running', 'paused', 'error'] as const;
export const TRADING_MODES = ['paper', 'testnet', 'live'] as const;
export const COMMAND_TYPES = [
  'start',
  'pause',
  'resume',
  'stop',
  'emergency_stop',
  'close_position',
] as const;
export const COMMAND_STATUSES = ['pending', 'processing', 'completed', 'failed'] as const;
export const EVENT_LEVELS = ['debug', 'info', 'warn', 'error', 'critical'] as const;
export const ORDER_SIDES = ['buy', 'sell'] as const;
export const ORDER_TYPES = ['market', 'limit', 'stop_loss_limit', 'take_profit_limit'] as const;
export const ORDER_STATUSES = [
  'new',
  'partially_filled',
  'filled',
  'canceled',
  'rejected',
  'expired',
  'pending',
  'failed',
] as const;
export const POSITION_STATUSES = ['open', 'closed'] as const;
export const POSITION_SIDES = ['long', 'short'] as const;

export const TIMEFRAMES = ['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '1d'] as const;

export const STRATEGIES = ['ema_rsi'] as const;

/** Binance Spot taker fee (0.1 %) used by the paper broker. */
export const BINANCE_SPOT_TAKER_FEE = 0.001;

/** Default slippage assumption for simulated market orders (0.05 %). */
export const DEFAULT_PAPER_SLIPPAGE = 0.0005;

/** Heartbeat interval of the worker in milliseconds. */
export const HEARTBEAT_INTERVAL_MS = 20_000;

/** How often the worker polls system_commands (ms). */
export const COMMAND_POLL_INTERVAL_MS = 2_000;

/** How often the worker re-syncs Binance server time (ms). */
export const TIME_SYNC_INTERVAL_MS = 5 * 60_000;

/** How often local orders are reconciled against the exchange (ms). */
export const RECONCILE_INTERVAL_MS = 60_000;

/** A bot heartbeat older than this is considered stale (ms). */
export const HEARTBEAT_STALE_MS = 90_000;

/** Prefix for every clientOrderId generated by this system. */
export const CLIENT_ORDER_ID_PREFIX = 'dtb';

export const EXIT_REASONS = [
  'stop_loss',
  'take_profit',
  'trailing_stop',
  'opposite_signal',
  'emergency_stop',
  'manual_close',
  'shutdown',
] as const;

export const DISCLAIMER =
  'Trading involves substantial risk. This software does not guarantee profits. ' +
  'Testnet and paper trading only — no real funds are used.';
